DATA_SEG	SEGMENT
FIVE		DB 5D
DATA_LIST	DW -1, 0, 2, 5, 4, 5 DUP (?)
MAX 		DW ?
MIN 		DW ?
DATA_SEG 	ENDS
CODE	SEGMENT
MAIN			PROC	FAR
				ASSUME CS:CODE, DS:DATA_SEG
				MOV	AX, DATA_SEG
				MOV DS, AX
				MOV DX, DATA_LIST[0]
				MOV MAX, DX
				MOV MIN, DX
				MOV SI, 8
	LP:			MOV DX, DATA_LIST[SI]
				CMP MAX, DX
				JL	CHANGE_MAX
				JMP JUDGE_MIN
	JUDGE_MIN:	MOV DX, DATA_LIST[SI]
				CMP MIN, DX
				JG CHANGE_MIN
				JMP NEXT
	CHANGE_MAX: MOV DX, DATA_LIST[SI]
				MOV MAX, DX
				JMP NEXT
	CHANGE_MIN: MOV DX, DATA_LIST[SI]
				MOV MIN, DX
				JMP NEXT
	NEXT:		SUB SI, 2
				CMP SI, 0
				JGE	LP
				MOV BX, MAX
				MOV DX, MIN
				MOV AX, 4C00H
				INT 21H
MAIN 			ENDP
CODE			ENDS
				END 	MAIN