DATA SEGMENT AT 0E000H							; 数据段的位置从 0E000H 开始
	ARRAY_B LABEL BYTE							; 不同类型同一起始地址
	ARRAY_W DW 50 DUP (?)
DATA ENDS

STACK SEGMENT PARA STACK 'STACK'
	TOP LABEL BYTE
	BASE DB 100 DUP (?)
STACK ENDS

CODE SEGMENT 
	ASSUME CS:CODE, DS:DATA, SS:STACK			; 段指定
	ORG 1000H									; 指定主程序从 1000H 开始
START: 		
	MOV AX, DATA
	MOV DS, AX
	; your code here
	MOV AX, 4C00H
	INT 21H

CODE ENDS
	END START
