D_SEG SEGMENT
	AUGEND DD 99251
	SUM DD ?
D_SEG ENDS

E_SEG SEGMENT
	ADDEND DD -15962
E_SEG ENDS

CODE SEGMENT
	ASSUME CS:CODE, DS:D_SEG, ES:E_SEG
START:
	MOV AX, D_SEG
	MOV DS, AX
	MOV AX, E_SEG
	MOV ES, AX
	MOV AX, WORD PTR AUGEND
	MOV DX, WORD PTR ADDEND
	ADD AX, DX
	MOV BX, WORD PTR AUGEND[2]
	MOV DX, WORD PTR ADDEND[2]
	ADC BX, DX
	MOV WORD PTR SUM, AX
	MOV WORD PTR SUM[2], BX

	MOV AX, 4C00H
	INT 21H
CODE ENDS
	END START

; SUM IN DS:0004,  59 45 01 00