 DATA SEGMENT 
    PARTNO DW 0
    PNAME DB 16 DUP(0)
    COUNT DD 0
    PLENTH EQU $-PARTNO
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX

    MOV BX, PLENTH	;PLENTH的值为22，表示三个变量占的内存大小，单位为字节

    MOV AH, 04CH
    INT 21H	
CODE ENDS
    END START